### ISSUE TITLE
As an Employer, I want employer profile details to be stored separately from basic User data so that employers can have profile details specific to employers (e.g. department, agency).

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/fall2019-cs-gy-6063-team-one#165] opened 2019-10-31 22:22 UTC
**Employer**:
- _Department_ (fk, required)

Extends from **CustomUser**

**Comment by jackxujh** [comment] 2019-10-31 22:28
Is this a duplicate of #153 ?

**Closed** 2019-11-13 22:20 UTC
